//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WEB_DATAEntities : DbContext
    {
        public WEB_DATAEntities()
            : base("name=WEB_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DM_DONHANG> DM_DONHANG { get; set; }
        public DbSet<DM_DONHANG_CHITIET> DM_DONHANG_CHITIET { get; set; }
        public DbSet<DM_DONHANG_HINHTHUCTHANHTOAN> DM_DONHANG_HINHTHUCTHANHTOAN { get; set; }
        public DbSet<DM_DONHANG_TRANGTHAI> DM_DONHANG_TRANGTHAI { get; set; }
        public DbSet<DM_KHACHHANG> DM_KHACHHANG { get; set; }
        public DbSet<DM_KM> DM_KM { get; set; }
        public DbSet<DM_KM_CT> DM_KM_CT { get; set; }
        public DbSet<DM_KM_HINHTHUC> DM_KM_HINHTHUC { get; set; }
        public DbSet<DM_SANPHAM> DM_SANPHAM { get; set; }
        public DbSet<DM_SANPHAM_NHOM> DM_SANPHAM_NHOM { get; set; }
        public DbSet<DM_TAIKHOAN> DM_TAIKHOAN { get; set; }
        public DbSet<DM_SANPHAM_CHITIET> DM_SANPHAM_CHITIET { get; set; }
        public DbSet<DM_THUONGHIEU> DM_THUONGHIEU { get; set; }
        public DbSet<DM_KHACHHANG_DIACHI> DM_KHACHHANG_DIACHI { get; set; }
    
        public virtual int SP_CHECKOUT(Nullable<int> flag, string maKhach, string diaChi, Nullable<bool> danhDauMacDinh, string maDiaChi)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var maKhachParameter = maKhach != null ?
                new ObjectParameter("maKhach", maKhach) :
                new ObjectParameter("maKhach", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("diaChi", diaChi) :
                new ObjectParameter("diaChi", typeof(string));
    
            var danhDauMacDinhParameter = danhDauMacDinh.HasValue ?
                new ObjectParameter("danhDauMacDinh", danhDauMacDinh) :
                new ObjectParameter("danhDauMacDinh", typeof(bool));
    
            var maDiaChiParameter = maDiaChi != null ?
                new ObjectParameter("maDiaChi", maDiaChi) :
                new ObjectParameter("maDiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECKOUT", flagParameter, maKhachParameter, diaChiParameter, danhDauMacDinhParameter, maDiaChiParameter);
        }
    
        public virtual ObjectResult<SP_DANGNHAP_Result> SP_DANGNHAP(Nullable<int> flag, string ten, string matkhau)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DANGNHAP_Result>("SP_DANGNHAP", flagParameter, tenParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<SP_GIOHANG_Result> SP_GIOHANG(Nullable<int> flag, string maDonHang, string maSanPham, string maChiTietDonHang, Nullable<double> soLuong, Nullable<double> thanhTien, string mau, string size, string maKhach)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var maDonHangParameter = maDonHang != null ?
                new ObjectParameter("maDonHang", maDonHang) :
                new ObjectParameter("maDonHang", typeof(string));
    
            var maSanPhamParameter = maSanPham != null ?
                new ObjectParameter("maSanPham", maSanPham) :
                new ObjectParameter("maSanPham", typeof(string));
    
            var maChiTietDonHangParameter = maChiTietDonHang != null ?
                new ObjectParameter("maChiTietDonHang", maChiTietDonHang) :
                new ObjectParameter("maChiTietDonHang", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(double));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("thanhTien", thanhTien) :
                new ObjectParameter("thanhTien", typeof(double));
    
            var mauParameter = mau != null ?
                new ObjectParameter("mau", mau) :
                new ObjectParameter("mau", typeof(string));
    
            var sizeParameter = size != null ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(string));
    
            var maKhachParameter = maKhach != null ?
                new ObjectParameter("maKhach", maKhach) :
                new ObjectParameter("maKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GIOHANG_Result>("SP_GIOHANG", flagParameter, maDonHangParameter, maSanPhamParameter, maChiTietDonHangParameter, soLuongParameter, thanhTienParameter, mauParameter, sizeParameter, maKhachParameter);
        }
    
        public virtual ObjectResult<SP_HOMEPAGE_Result> SP_HOMEPAGE(Nullable<int> flag, string manhom, string session, string madonhang, string makhach, string masanpham, Nullable<double> soluong, string size, string mau, string muihuong, string dungtich, string text)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var manhomParameter = manhom != null ?
                new ObjectParameter("manhom", manhom) :
                new ObjectParameter("manhom", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var madonhangParameter = madonhang != null ?
                new ObjectParameter("madonhang", madonhang) :
                new ObjectParameter("madonhang", typeof(string));
    
            var makhachParameter = makhach != null ?
                new ObjectParameter("makhach", makhach) :
                new ObjectParameter("makhach", typeof(string));
    
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(double));
    
            var sizeParameter = size != null ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(string));
    
            var mauParameter = mau != null ?
                new ObjectParameter("mau", mau) :
                new ObjectParameter("mau", typeof(string));
    
            var muihuongParameter = muihuong != null ?
                new ObjectParameter("muihuong", muihuong) :
                new ObjectParameter("muihuong", typeof(string));
    
            var dungtichParameter = dungtich != null ?
                new ObjectParameter("dungtich", dungtich) :
                new ObjectParameter("dungtich", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HOMEPAGE_Result>("SP_HOMEPAGE", flagParameter, manhomParameter, sessionParameter, madonhangParameter, makhachParameter, masanphamParameter, soluongParameter, sizeParameter, mauParameter, muihuongParameter, dungtichParameter, textParameter);
        }
    }
}
