//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEB_DATAEntities : DbContext
    {
        public WEB_DATAEntities()
            : base("name=WEB_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DM_DONHANG> DM_DONHANG { get; set; }
        public DbSet<DM_DONHANG_CHITIET> DM_DONHANG_CHITIET { get; set; }
        public DbSet<DM_DONHANG_HINHTHUCTHANHTOAN> DM_DONHANG_HINHTHUCTHANHTOAN { get; set; }
        public DbSet<DM_DONHANG_TRANGTHAI> DM_DONHANG_TRANGTHAI { get; set; }
        public DbSet<DM_KHACHHANG> DM_KHACHHANG { get; set; }
        public DbSet<DM_KM> DM_KM { get; set; }
        public DbSet<DM_KM_CT> DM_KM_CT { get; set; }
        public DbSet<DM_KM_HINHTHUC> DM_KM_HINHTHUC { get; set; }
        public DbSet<DM_SANPHAM> DM_SANPHAM { get; set; }
        public DbSet<DM_SANPHAM_NHOM> DM_SANPHAM_NHOM { get; set; }
        public DbSet<DM_TAIKHOAN> DM_TAIKHOAN { get; set; }
    }
}
