//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHITIETSANPHAM
    {
        public string MASANPHAM { get; set; }
        public string SIZE { get; set; }
        public string MAU { get; set; }
        public string DUNGTICH { get; set; }
        public string DOITUONGSUDUNG { get; set; }
    }
}
