//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DONHANG_CHITIET
    {
        public string MADONHANG { get; set; }
        public string MACHITIETDONHANG { get; set; }
        public string MASANPHAM { get; set; }
        public Nullable<double> SOLUONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<double> SALE { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public string TENSANPHAM { get; set; }
        public string SIZE { get; set; }
        public string MAU { get; set; }
        public string DUNGTICH { get; set; }
        public string LOAI { get; set; }
        public string MUIHUONG { get; set; }
    }
}
