//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DONHANG_HINHTHUCTHANHTOAN
    {
        public string MAHINHTHUCTHANHTOAN { get; set; }
        public string TENHINHTHUCTHANHTOAN { get; set; }
    }
}
