//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DONHANG
    {
        public string MADONHANG { get; set; }
        public string MAKHACHHANG { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string MATRANGTHAI { get; set; }
        public string MAXACNHAN { get; set; }
        public string TONGTIEN { get; set; }
        public string MAHINHTHUCTHANHTOAN { get; set; }
    }
}
