//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KM_CT
    {
        public string MAKHUYENMAI { get; set; }
        public string MACHITIETKHUYENMAI { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public Nullable<double> PHANTRAM { get; set; }
        public string MANHOM { get; set; }
    }
}
