//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHACHHANG_DIACHI
    {
        public string MADIACHI { get; set; }
        public string MAKHACHHANG { get; set; }
        public string DIACHI { get; set; }
        public Nullable<bool> MACDINH { get; set; }
        public string TENNGUOINHAN { get; set; }
        public string SDTNGUOINHAN { get; set; }
    }
}
