//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SANPHAM
    {
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string MANHOM { get; set; }
        public Nullable<double> GIA1 { get; set; }
        public Nullable<double> GIA2 { get; set; }
        public string DONVI { get; set; }
        public string MACHITIETSANPHAM { get; set; }
    }
}
