//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class THE
    {
        public string MATHE { get; set; }
        public string TENCHUTHE { get; set; }
        public string THANG { get; set; }
        public string NAM { get; set; }
        public Nullable<double> TIEN { get; set; }
        public string CCV { get; set; }
    }
}
